version: '2'

services:
  web-node:
    image:
      stevelasker/web-node:latest
    ports:
      - "8080:3000"
    environment:
      - HTTPPORT=3000
      - APIPORT=5000
    depends_on:
      - api-dotnet
  api-dotnet:
    image:
      stevelasker/api-dotnet:latest
    ports:
      - "5000:5000"