version: '2'

services:
  web-node:
    image:
      stevelasker/web-node:latest
    ports:
      - "8080:8080"
    depends_on:
      - api-dotnet
  api-dotnet:
    image:
      stevelasker/api-dotnet:latest
    ports:
      - "5000:5000"